#!/usr/bin/env bash
# Deploy an event's MDBook report to GitHub Pages.
#
# Usage: deploy-book.sh <event>
#
# Structure on gh-pages branch:
#   /index.html              Landing page (auto-generated, lists all events)
#   /<event>/index.html      Event briefing book
#   /.nojekyll               Bypass Jekyll processing
#
# Requires: mdbook, git
set -euo pipefail

EVENT="${1:?Usage: deploy-book.sh <event>}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
BOOK_SRC="${REPO_ROOT}/events/${EVENT}/reports/book"
BOOK_OUT="${BOOK_SRC}/book"

# ── Step 1: Build ──────────────────────────────────────────────────────────

if [[ ! -f "${BOOK_SRC}/book.toml" ]]; then
    echo "Error: No book.toml at ${BOOK_SRC}"
    echo "Run 'just report ${EVENT}' first to generate report sources."
    exit 1
fi

echo ":: Building mdBook for ${EVENT}..."
(cd "$BOOK_SRC" && mdbook build)

if [[ ! -f "${BOOK_OUT}/index.html" ]]; then
    echo "Error: mdbook build produced no output at ${BOOK_OUT}"
    exit 1
fi

# ── Step 2: Prepare gh-pages working copy ──────────────────────────────────

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

REMOTE_URL=$(git remote get-url origin)

if git ls-remote --exit-code --heads origin gh-pages &>/dev/null; then
    echo ":: Fetching existing gh-pages branch..."
    git clone --branch gh-pages --single-branch --depth 1 "$REMOTE_URL" "$TMPDIR/site"
else
    echo ":: Initializing new gh-pages branch..."
    mkdir -p "$TMPDIR/site"
    git -C "$TMPDIR/site" init -b gh-pages
    git -C "$TMPDIR/site" remote add origin "$REMOTE_URL"
fi

# ── Step 3: Copy event book ────────────────────────────────────────────────

echo ":: Copying ${EVENT} book..."
rm -rf "${TMPDIR}/site/${EVENT}"
cp -r "$BOOK_OUT" "${TMPDIR}/site/${EVENT}"
touch "${TMPDIR}/site/.nojekyll"

# ── Step 4: Generate landing page ──────────────────────────────────────────

echo ":: Generating landing page..."

EVENT_CARDS=""
for dir in "$TMPDIR/site"/*/; do
    name=$(basename "$dir")
    [[ "$name" == ".git" ]] && continue
    [[ ! -f "$dir/index.html" ]] && continue

    # Extract title from the book's index.html <title> tag
    title=$(sed -n 's/.*<title>\(.*\)<\/title>.*/\1/p' "$dir/index.html" | head -1)
    # Strip the leading "page name - " prefix mdBook adds
    title="${title##* - }"
    [[ -z "$title" ]] && title="$name"

    EVENT_CARDS="${EVENT_CARDS}        <a class=\"event-card\" href=\"${name}/\">
            <h2>${title}</h2>
            <span class=\"slug\">${name}</span>
        </a>
"
done

cat > "$TMPDIR/site/index.html" <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Conference Briefings</title>
    <style>
        :root {
            --bg: #fff; --fg: #1a1a1a; --muted: #666;
            --border: #e0e0e0; --card-bg: #f8f9fa; --link: #0969da;
        }
        @media (prefers-color-scheme: dark) {
            :root {
                --bg: #0d1117; --fg: #e6edf3; --muted: #8b949e;
                --border: #30363d; --card-bg: #161b22; --link: #58a6ff;
            }
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            background: var(--bg); color: var(--fg);
            line-height: 1.6; max-width: 720px; margin: 0 auto; padding: 3rem 1.5rem;
        }
        h1 { font-size: 1.75rem; margin-bottom: 0.25rem; }
        .subtitle { color: var(--muted); margin-bottom: 2.5rem; font-size: 1.05rem; }
        .events { display: flex; flex-direction: column; gap: 0.75rem; }
        .event-card {
            display: block; text-decoration: none; color: var(--fg);
            background: var(--card-bg); border: 1px solid var(--border);
            border-radius: 6px; padding: 1.25rem 1.5rem;
            transition: border-color 0.15s;
        }
        .event-card:hover { border-color: var(--link); }
        .event-card h2 { font-size: 1.15rem; color: var(--link); margin-bottom: 0.15rem; }
        .event-card .slug { color: var(--muted); font-size: 0.85rem; font-family: ui-monospace, monospace; }
        footer {
            margin-top: 3rem; padding-top: 1.25rem;
            border-top: 1px solid var(--border);
            color: var(--muted); font-size: 0.85rem;
        }
        footer a { color: var(--link); text-decoration: none; }
        footer a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>Conference Briefings</h1>
    <p class="subtitle">AI-powered conference intelligence reports</p>
    <div class="events">
${EVENT_CARDS}    </div>
    <footer>
        Generated by <a href="https://github.com/leonardpahlke/conf-briefing">conf-briefing</a>
    </footer>
</body>
</html>
HTMLEOF

# ── Step 5: Commit and push ───────────────────────────────────────────────

cd "$TMPDIR/site"

GIT_USER=$(git -C "$REPO_ROOT" config user.name 2>/dev/null || echo "conf-briefing")
GIT_EMAIL=$(git -C "$REPO_ROOT" config user.email 2>/dev/null || echo "noreply@conf-briefing")
git config user.name "$GIT_USER"
git config user.email "$GIT_EMAIL"

git add -A

if git diff --cached --quiet 2>/dev/null; then
    echo ":: No changes to deploy."
    exit 0
fi

git commit -m "deploy: ${EVENT} intelligence briefing"
git push origin gh-pages

REPO_NAME=$(basename "$REPO_ROOT")
GH_USER=$(echo "$REMOTE_URL" | sed -n 's|.*[:/]\([^/]*\)/.*|\1|p')

echo ""
echo "Deployed ${EVENT} to gh-pages."
echo ""
echo "  https://${GH_USER}.github.io/${REPO_NAME}/${EVENT}/"
echo ""
echo "If this is your first deploy, enable GitHub Pages:"
echo "  Repo Settings > Pages > Source: Deploy from branch > gh-pages"
